version: '3.6'

services:
  arke-maker:
    restart: always
    image: "quay.io/openware/arke:2.6.0-bccb72c"
    env_file:
      - ../config/arke.env
    volumes:
      - ../config/arke/strategies.yml:/home/app/config/strategies.yml
    command: bundle exec ./bin/arke start
