version: '3.6'

services:
  parity:
    image: parity/parity:v2.7.2-stable
    restart: always
    command: |
      --chain=kovan
      --mode=active
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
      --no-persistent-txqueue
    volumes:
      - ../data/parity:/home/parity/.local/share/io.parity.ethereum
    ports:
      - "127.0.0.1:8545:8545"

  bitcoind:
    image: quay.io/openware/bitcoind:0.19.1
    restart: always
    user: root
    command: bitcoind
    volumes:
      - ../data/bitcoin:/bitcoin
      - ../config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  litecoind:
    image: quay.io/openware/litecoind:0.16.3
    restart: always
    volumes:
      - ../data/litecoin:/litecoin
      - ../config/litecoin.conf:/litecoin/litecoin.conf
