version: '3.6'

services:
  gateway:
    restart: always
    image: envoyproxy/envoy:v1.10.0
    volumes:
      - ../config/gateway:/etc/envoy/
    command: /usr/local/bin/envoy -l info -c /etc/envoy/envoy.yaml
    labels:
      - "traefik.http.routers.gateway-siamchain.rule=Host(`www.siamchain.com`) && PathPrefix(`/api`,`/admin`,`/assets/`)"
      - "traefik.enable=true"
      - "traefik.http.services.gateway-siamchain.loadbalancer.server.port=8099"
      - "traefik.http.routers.gateway-siamchain.entrypoints=websecure"
      - "traefik.http.routers.gateway-siamchain.tls=true"
      - "traefik.http.routers.gateway-siamchain.tls.certresolver=myresolver"
